version: "2.0"
services:

#  THis is HA proxy for setup
#  TODO:  Changes ip rule for HA across machines
    proxy:
        build: ./proxy
        ports:
            - "80:80"
            - "443:443"

# THis is fpm server  for php application
# TODO:  setup multiple sites using configuration			
    php:
       image: php:7.0-fpm
       expose:
            - "9000"

## Add configuration files volume			
    cuckoo_proxy:
        image: tianon/true

    cuckoo_php:
        image: tianon/true