FROM nginx:1.10.2

MAINTAINER Mahesh Attarde<mahesh@shoppitron.com>
ADD nginx.conf /etc/nginx/
COPY sites-available/*.conf /etc/nginx/sites-available/
ARG PHP_UPSTREAM=php-fpm
RUN rm /etc/nginx/conf.d/default.conf \
    && echo "upstream php-upstream { server ${PHP_UPSTREAM}:9000; }" > /etc/nginx/conf.d/upstream.conf
CMD ["nginx"]
EXPOSE 80 443