FROM php:7.0-fpm
MAINTAINER Mahesh Attarde<mahesh@shoppitron.com>

# Copy Php Configurations
# TODO : changes this  ini to production

ADD  ./dev_php.ini /usr/local/etc/php/conf.d
COPY ./dev_pool.conf /usr/local/etc/php-fpm.d/www.conf
## THIS DEV version
COPY ./php-fpm.conf  ./usr/local/etc/php-fpm.conf
RUN touch /usr/local/var/log/www.access.log

# TODO :  this are dev libaries test against  prod
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        libmemcached-dev \
        libz-dev \
        libpq-dev \
        libjpeg-dev \
        libpng12-dev \
        libfreetype6-dev \
        libssl-dev \
        libmcrypt-dev

# Install the PHP mcrypt extention
RUN docker-php-ext-install mcrypt

# Install the PHP pdo_mysql extention
RUN docker-php-ext-install pdo_mysql

# Install the PHP pdo_pgsql extention
RUN docker-php-ext-install pdo_pgsql


# Install the PHP gd library
RUN docker-php-ext-configure gd \
        --enable-gd-native-ttf \
        --with-jpeg-dir=/usr/lib \
        --with-freetype-dir=/usr/include/freetype2 && \
    docker-php-ext-install gd

RUN rm -r /var/lib/apt/lists/*

RUN usermod -u 1000 www-data

WORKDIR /var/www/shoppitron

CMD ["php-fpm"]

EXPOSE 9000	
	
		